"use client";

import Image from "next/image";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
import { Activity, Bell, Boxes, ChevronRight, CircleDollarSign, ClipboardList, FileBox, FileText, Gauge, HelpCircle, LayoutTemplate, LogOut, Mail, Menu, Package, Receipt, Search, Settings, ShieldCheck, Star, Tags, Users, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { logoutAction } from "@/app/(auth)/actions";
import { cn } from "@/lib/utils";

export type NavIconName = "activity" | "bell" | "boxes" | "billing" | "clipboard" | "file-box" | "file-text" | "gauge" | "help" | "layout" | "mail" | "package" | "receipt" | "settings" | "shield" | "star" | "tags" | "users";
export type NavItem = { label: string; href: string; icon: NavIconName };
const navIcons = { activity: Activity, bell: Bell, boxes: Boxes, billing: CircleDollarSign, clipboard: ClipboardList, "file-box": FileBox, "file-text": FileText, gauge: Gauge, help: HelpCircle, layout: LayoutTemplate, mail: Mail, package: Package, receipt: Receipt, settings: Settings, shield: ShieldCheck, star: Star, tags: Tags, users: Users } as const;

export function DashboardShell({ children, nav, name, subtitle, admin = false }: { children: React.ReactNode; nav: readonly NavItem[]; name: string; subtitle: string; admin?: boolean }) {
  const [open, setOpen] = useState(false);
  const path = usePathname();
    const sidebar = <div className="flex h-full flex-col bg-slate-950 text-slate-200"><div className="flex h-18 items-center justify-between border-b border-slate-800 px-5"><Link href="/" className="flex items-center gap-2.5"><Image src="/assets/nexora-logo.png" alt="" width={38} height={38} className="rounded-xl"/><span className="text-lg font-extrabold text-white">Nexora</span></Link><button className="lg:hidden" onClick={() => setOpen(false)} aria-label="Close navigation"><X/></button></div><nav className="flex-1 space-y-1 overflow-y-auto p-3">{nav.map(({ label, href, icon }) => { const Icon = navIcons[icon]; return <Link key={href} href={href} onClick={() => setOpen(false)} className={cn("flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition", path === href ? "bg-blue-600 text-white" : "text-slate-400 hover:bg-slate-900 hover:text-white")}><Icon className="h-4 w-4"/>{label}</Link>; })}</nav><div className="border-t border-slate-800 p-3"><form action={logoutAction}><button className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-slate-400 hover:bg-slate-900 hover:text-white"><LogOut className="h-4 w-4"/>Log out</button></form></div></div>;
  return <div className="min-h-screen bg-slate-50"><aside className="fixed inset-y-0 left-0 z-40 hidden w-64 lg:block">{sidebar}</aside>{open&&<><button aria-label="Close menu overlay" className="fixed inset-0 z-40 bg-slate-950/50 lg:hidden" onClick={()=>setOpen(false)}/><aside className="fixed inset-y-0 left-0 z-50 w-72 lg:hidden">{sidebar}</aside></>}<div className="lg:pl-64"><header className="sticky top-0 z-30 flex h-18 items-center gap-3 border-b bg-white/95 px-4 backdrop-blur sm:px-6"><Button variant="ghost" size="icon" className="lg:hidden" onClick={()=>setOpen(true)}><Menu/></Button><div className="hidden max-w-sm flex-1 md:block"><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><Input className="h-9 rounded-xl bg-slate-50 pl-9" placeholder="Search workspace..."/></div></div><div className="ml-auto flex items-center gap-3"><Button variant="ghost" size="icon" className="relative rounded-full"><Bell className="h-5 w-5"/><span className="absolute right-2 top-2 h-2 w-2 rounded-full bg-blue-600"/></Button><div className="hidden text-right sm:block"><p className="text-sm font-bold">{name}</p><p className="text-xs text-slate-500">{subtitle}</p></div><div className="grid h-9 w-9 place-items-center rounded-full bg-blue-100 text-sm font-bold text-blue-700">{name.slice(0,2).toUpperCase()}</div></div></header><div className="border-b bg-white px-4 py-3 text-xs text-slate-500 sm:px-6"><span>{admin?"Admin":"Customer"}</span><ChevronRight className="mx-1 inline h-3 w-3"/><span className="font-semibold text-slate-700">{nav.find(n=>n.href===path)?.label??"Overview"}</span></div><main className="p-4 sm:p-6 lg:p-8">{children}</main></div></div>;
}
