import Image from "next/image";
import Link from "next/link";
import { redirect } from "next/navigation";
import { z } from "zod";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

const requestSchema=z.object({title:z.string().min(3).max(120),platform:z.string().min(2).max(50),contentType:z.string().min(2).max(50),description:z.string().min(10).max(5000),targetAudience:z.string().max(500).optional(),desiredTone:z.string().max(200).optional(),deadline:z.coerce.date().optional()});
const titles:Record<string,string>={subscription:"My subscription",package:"My package",orders:"Orders",invoices:"Invoices",payments:"Payments",requests:"Content requests",deliveries:"Delivered content",notifications:"Notifications",profile:"Profile",support:"Support"};
export const dynamic="force-dynamic";
export default async function CustomerSection({params}:{params:Promise<{section:string[]}>}){const user=await requireUser();const parts=(await params).section;const key=parts[0];if(key==="requests"&&parts[1]==="new"){async function create(formData:FormData){"use server";const current=await requireUser();const parsed=requestSchema.safeParse(Object.fromEntries(formData));if(!parsed.success)throw new Error("Please check the request fields");await prisma.contentRequest.create({data:{userId:current.id,...parsed.data,attachmentUrls:[]}});redirect("/dashboard/requests")}return <div className="mx-auto max-w-3xl"><Link href="/dashboard/requests" className="text-sm font-bold text-primary">← Back to requests</Link><h1 className="mt-4 text-3xl font-extrabold">New content request</h1><p className="mt-2 text-slate-500">Give the team the context needed to produce strong work.</p><Card className="mt-7 rounded-2xl border-0 shadow-sm"><CardContent className="p-6"><form action={create} className="grid gap-5 sm:grid-cols-2"><Field name="title" label="Request title" placeholder="Ramadan campaign posts"/><Field name="platform" label="Platform" placeholder="Instagram"/><Field name="contentType" label="Content type" placeholder="Carousel posts"/><Field name="deadline" label="Desired deadline" type="date"/><div className="sm:col-span-2"><Label htmlFor="description">Description</Label><Textarea id="description" name="description" required minLength={10} className="mt-2 min-h-32 rounded-xl" placeholder="Describe the objective, offer, and key message..."/></div><Field name="targetAudience" label="Target audience" placeholder="Families in Amman"/><Field name="desiredTone" label="Desired tone" placeholder="Warm and confident"/><div className="sm:col-span-2 rounded-xl border border-dashed bg-slate-50 p-4 text-sm text-slate-500">Secure attachments become available after storage credentials are configured. Your request can be submitted now and files added later.</div><div className="sm:col-span-2 flex justify-end"><Button className="rounded-xl">Submit request</Button></div></form></CardContent></Card></div>}
  const data=await getSectionData(key,user.id);return <div className="mx-auto max-w-7xl"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-wide text-primary">Customer workspace</p><h1 className="mt-1 text-3xl font-extrabold">{titles[key]??"Workspace"}</h1></div>{key==="requests"&&<Button className="rounded-xl" asChild><Link href="/dashboard/requests/new">New request</Link></Button>}</div><Card className="mt-7 rounded-2xl border-0 shadow-sm"><CardHeader><CardTitle className="text-lg">{data.length?`${data.length} record${data.length===1?"":"s"}`:"Nothing here yet"}</CardTitle></CardHeader><CardContent>{data.length?<div className="divide-y">{data.map((row,i)=><div key={row.id??i} className="flex flex-col justify-between gap-2 py-4 sm:flex-row sm:items-center"><div><p className="font-semibold">{row.title}</p><p className="mt-1 text-sm text-slate-500">{row.detail}</p></div><span className="w-fit rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">{row.status}</span></div>)}</div>:<div className="flex min-h-72 flex-col items-center justify-center rounded-2xl border border-dashed bg-slate-50 p-8 text-center"><Image src="/assets/content-empty-state.png" alt="" width={150} height={120} className="mb-3 rounded-2xl"/><p className="font-bold">No data available</p><p className="mt-1 max-w-md text-sm text-slate-500">Records created in your Nexora workspace will appear here.</p></div>}</CardContent></Card></div>}
function Field({name,label,...props}:{name:string;label:string}&React.ComponentProps<typeof Input>){return <div><Label htmlFor={name}>{label}</Label><Input id={name} name={name} className="mt-2 h-11 rounded-xl" {...props}/></div>}
type Row={id?:string;title:string;detail:string;status:string};
async function getSectionData(key:string,userId:string):Promise<Row[]>{if(key==="orders")return (await prisma.order.findMany({where:{userId},orderBy:{createdAt:"desc"}})).map(x=>({id:x.id,title:x.orderNumber,detail:`${Number(x.amount).toFixed(3)} ${x.currency}`,status:x.status}));if(key==="payments")return (await prisma.payment.findMany({where:{userId},orderBy:{createdAt:"desc"}})).map(x=>({id:x.id,title:`${Number(x.amount).toFixed(3)} ${x.currency}`,detail:x.provider,status:x.status}));if(key==="invoices")return (await prisma.invoice.findMany({where:{userId},orderBy:{createdAt:"desc"}})).map(x=>({id:x.id,title:x.invoiceNumber,detail:`${Number(x.total).toFixed(3)} ${x.currency}`,status:x.status}));if(key==="requests")return (await prisma.contentRequest.findMany({where:{userId},orderBy:{createdAt:"desc"}})).map(x=>({id:x.id,title:x.title,detail:`${x.platform} · ${x.contentType}`,status:x.status.replaceAll("_"," ")}));if(key==="notifications")return (await prisma.notification.findMany({where:{userId},orderBy:{createdAt:"desc"}})).map(x=>({id:x.id,title:x.title,detail:x.message,status:x.readAt?"READ":"NEW"}));if(key==="deliveries")return (await prisma.contentDelivery.findMany({where:{contentRequest:{userId}},orderBy:{createdAt:"desc"}})).map(x=>({id:x.id,title:x.title,detail:x.message??"Delivered content",status:"DELIVERED"}));return []}
